import { ReceiverDataType } from "@repo/ui";

export const RECEIVER_DATA: ReceiverDataType[] = [
  {
    unit_no: "NTM 017",
    postcode: "NE 1",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 1,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 132",
    postcode: "NE 14",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 2,
    listening_time: "0hr37mins29secs",
  },
  {
    unit_no: "NTM 009",
    postcode: "NE 7",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 3,
    listening_time: "5hr28mins12secs",
  },
  {
    unit_no: "NTM 076",
    postcode: "NE 16",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 4,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 184",
    postcode: "NE 1",
    status: false,
    last_broadcast: "23/05/2024",
    transmission_strength: 0,
    listening_time: "7hr32mins18secs",
  },
  {
    unit_no: "NTM 068",
    postcode: "NE 9",
    status: false,
    last_broadcast: "23/05/2024",
    transmission_strength: 0,
    listening_time: "17hr2mins30secs",
  },
  {
    unit_no: "NTM 242",
    postcode: "NE 11",
    status: false,
    last_broadcast: "22/05/2024",
    transmission_strength: 0,
    listening_time: "8hr29mins24secs",
  },
  {
    unit_no: "NTM 027",
    postcode: "NE 5",
    status: false,
    last_broadcast: "20/05/2024",
    transmission_strength: 0,
    listening_time: "22hr25mins41secs",
  },
  {
    unit_no: "NTM 114",
    postcode: "NE 7",
    status: false,
    last_broadcast: "19/05/2024",
    transmission_strength: 0,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 190",
    postcode: "NE 2",
    status: false,
    last_broadcast: "16/05/2024",
    transmission_strength: 0,
    listening_time: "21hr53mins44secs",
  },
  {
    unit_no: "NTM 025",
    postcode: "NE 15",
    status: false,
    last_broadcast: "16/05/2024",
    transmission_strength: 0,
    listening_time: "1hr53mins44secs",
  },
  // Additional entries to reach a total of 30
  {
    unit_no: "NTM 101",
    postcode: "NE 3",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 5,
    listening_time: "2hr10mins30secs",
  },
  {
    unit_no: "NTM 202",
    postcode: "NE 4",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 3,
    listening_time: "3hr15mins45secs",
  },
  {
    unit_no: "NTM 303",
    postcode: "NE 5",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 4,
    listening_time: "4hr20mins50secs",
  },
  {
    unit_no: "NTM 404",
    postcode: "NE 6",
    status: false,
    last_broadcast: "15/05/2024",
    transmission_strength: 0,
    listening_time: "5hr30mins15secs",
  },
  {
    unit_no: "NTM 505",
    postcode: "NE 8",
    status: false,
    last_broadcast: "14/05/2024",
    transmission_strength: 0,
    listening_time: "6hr40mins25secs",
  },
  {
    unit_no: "NTM 606",
    postcode: "NE 10",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 1,
    listening_time: "2hr50mins10secs",
  },
  {
    unit_no: "NTM 707",
    postcode: "NE 12",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 2,
    listening_time: "3hr30mins20secs",
  },
  {
    unit_no: "NTM 808",
    postcode: "NE 13",
    status: false,
    last_broadcast: "13/05/2024",
    transmission_strength: 0,
    listening_time: "4hr15mins35secs",
  },
  {
    unit_no: "NTM 909",
    postcode: "NE 14",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 5,
    listening_time: "5hr25mins45secs",
  },
  {
    unit_no: "NTM 010",
    postcode: "NE 15",
    status: false,
    last_broadcast: "12/05/2024",
    transmission_strength: 0,
    listening_time: "6hr50mins50secs",
  },
  {
    unit_no: "NTM 111",
    postcode: "NE 16",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 4,
    listening_time: "7hr15mins15secs",
  },
  {
    unit_no: "NTM 212",
    postcode: "NE 17",
    status: false,
    last_broadcast: "11/05/2024",
    transmission_strength: 0,
    listening_time: "8hr30mins30secs",
  },
  {
    unit_no: "NTM 313",
    postcode: "NE 18",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 2,
    listening_time: "9hr45mins45secs",
  },
  {
    unit_no: "NTM 414",
    postcode: "NE 19",
    status: false,
    last_broadcast: "10/05/2024",
    transmission_strength: 0,
    listening_time: "10hr20mins20secs",
  },
  {
    unit_no: "NTM 515",
    postcode: "NE 20",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 3,
    listening_time: "11hr5mins5secs",
  },
  {
    unit_no: "NTM 616",
    postcode: "NE 21",
    status: false,
    last_broadcast: "09/05/2024",
    transmission_strength: 0,
    listening_time: "12hr15mins15secs",
  },
  {
    unit_no: "NTM 717",
    postcode: "NE 22",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 4,
    listening_time: "13hr30mins30secs",
  },
  {
    unit_no: "NTM 818",
    postcode: "NE 23",
    status: false,
    last_broadcast: "08/05/2024",
    transmission_strength: 0,
    listening_time: "14hr45mins45secs",
  },
  {
    unit_no: "NTM 919",
    postcode: "NE 24",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 5,
    listening_time: "15hr10mins10secs",
  },
  {
    unit_no: "NTM 017",
    postcode: "NE 1",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 1,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 132",
    postcode: "NE 14",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 2,
    listening_time: "0hr37mins29secs",
  },
  {
    unit_no: "NTM 009",
    postcode: "NE 7",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 3,
    listening_time: "5hr28mins12secs",
  },
  {
    unit_no: "NTM 076",
    postcode: "NE 16",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 4,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 184",
    postcode: "NE 1",
    status: false,
    last_broadcast: "23/05/2024",
    transmission_strength: 0,
    listening_time: "7hr32mins18secs",
  },
  {
    unit_no: "NTM 068",
    postcode: "NE 9",
    status: false,
    last_broadcast: "23/05/2024",
    transmission_strength: 0,
    listening_time: "17hr2mins30secs",
  },
  {
    unit_no: "NTM 242",
    postcode: "NE 11",
    status: false,
    last_broadcast: "22/05/2024",
    transmission_strength: 0,
    listening_time: "8hr29mins24secs",
  },
  {
    unit_no: "NTM 027",
    postcode: "NE 5",
    status: false,
    last_broadcast: "20/05/2024",
    transmission_strength: 0,
    listening_time: "22hr25mins41secs",
  },
  {
    unit_no: "NTM 114",
    postcode: "NE 7",
    status: false,
    last_broadcast: "19/05/2024",
    transmission_strength: 0,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 190",
    postcode: "NE 2",
    status: false,
    last_broadcast: "16/05/2024",
    transmission_strength: 0,
    listening_time: "21hr53mins44secs",
  },
  {
    unit_no: "NTM 025",
    postcode: "NE 15",
    status: false,
    last_broadcast: "16/05/2024",
    transmission_strength: 0,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 101",
    postcode: "NE 3",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 5,
    listening_time: "2hr10mins30secs",
  },
  {
    unit_no: "NTM 202",
    postcode: "NE 4",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 3,
    listening_time: "3hr15mins45secs",
  },
  {
    unit_no: "NTM 303",
    postcode: "NE 5",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 2,
    listening_time: "4hr20mins50secs",
  },
  {
    unit_no: "NTM 404",
    postcode: "NE 6",
    status: false,
    last_broadcast: "15/05/2024",
    transmission_strength: 0,
    listening_time: "5hr30mins15secs",
  },
  {
    unit_no: "NTM 505",
    postcode: "NE 8",
    status: false,
    last_broadcast: "14/05/2024",
    transmission_strength: 0,
    listening_time: "6hr40mins25secs",
  },
  {
    unit_no: "NTM 606",
    postcode: "NE 10",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 4,
    listening_time: "2hr50mins10secs",
  },
  {
    unit_no: "NTM 017",
    postcode: "NE 1",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 1,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 132",
    postcode: "NE 14",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 2,
    listening_time: "0hr37mins29secs",
  },
  {
    unit_no: "NTM 009",
    postcode: "NE 7",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 3,
    listening_time: "5hr28mins12secs",
  },
  {
    unit_no: "NTM 076",
    postcode: "NE 16",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 4,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 184",
    postcode: "NE 1",
    status: false,
    last_broadcast: "23/05/2024",
    transmission_strength: 0,
    listening_time: "7hr32mins18secs",
  },
  {
    unit_no: "NTM 068",
    postcode: "NE 9",
    status: false,
    last_broadcast: "23/05/2024",
    transmission_strength: 0,
    listening_time: "17hr2mins30secs",
  },
  {
    unit_no: "NTM 242",
    postcode: "NE 11",
    status: false,
    last_broadcast: "22/05/2024",
    transmission_strength: 0,
    listening_time: "8hr29mins24secs",
  },
  {
    unit_no: "NTM 027",
    postcode: "NE 5",
    status: false,
    last_broadcast: "20/05/2024",
    transmission_strength: 0,
    listening_time: "22hr25mins41secs",
  },
  {
    unit_no: "NTM 114",
    postcode: "NE 7",
    status: false,
    last_broadcast: "19/05/2024",
    transmission_strength: 0,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 190",
    postcode: "NE 2",
    status: false,
    last_broadcast: "16/05/2024",
    transmission_strength: 0,
    listening_time: "21hr53mins44secs",
  },
  {
    unit_no: "NTM 025",
    postcode: "NE 15",
    status: false,
    last_broadcast: "16/05/2024",
    transmission_strength: 0,
    listening_time: "1hr53mins44secs",
  },
  // Additional entries to reach a total of 30
  {
    unit_no: "NTM 101",
    postcode: "NE 3",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 5,
    listening_time: "2hr10mins30secs",
  },
  {
    unit_no: "NTM 202",
    postcode: "NE 4",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 3,
    listening_time: "3hr15mins45secs",
  },
  {
    unit_no: "NTM 303",
    postcode: "NE 5",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 4,
    listening_time: "4hr20mins50secs",
  },
  {
    unit_no: "NTM 404",
    postcode: "NE 6",
    status: false,
    last_broadcast: "15/05/2024",
    transmission_strength: 0,
    listening_time: "5hr30mins15secs",
  },
  {
    unit_no: "NTM 505",
    postcode: "NE 8",
    status: false,
    last_broadcast: "14/05/2024",
    transmission_strength: 0,
    listening_time: "6hr40mins25secs",
  },
  {
    unit_no: "NTM 606",
    postcode: "NE 10",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 1,
    listening_time: "2hr50mins10secs",
  },
  {
    unit_no: "NTM 707",
    postcode: "NE 12",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 2,
    listening_time: "3hr30mins20secs",
  },
  {
    unit_no: "NTM 808",
    postcode: "NE 13",
    status: false,
    last_broadcast: "13/05/2024",
    transmission_strength: 0,
    listening_time: "4hr15mins35secs",
  },
  {
    unit_no: "NTM 909",
    postcode: "NE 14",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 5,
    listening_time: "5hr25mins45secs",
  },
  {
    unit_no: "NTM 010",
    postcode: "NE 15",
    status: false,
    last_broadcast: "12/05/2024",
    transmission_strength: 0,
    listening_time: "6hr50mins50secs",
  },
  {
    unit_no: "NTM 111",
    postcode: "NE 16",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 4,
    listening_time: "7hr15mins15secs",
  },
  {
    unit_no: "NTM 212",
    postcode: "NE 17",
    status: false,
    last_broadcast: "11/05/2024",
    transmission_strength: 0,
    listening_time: "8hr30mins30secs",
  },
  {
    unit_no: "NTM 313",
    postcode: "NE 18",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 2,
    listening_time: "9hr45mins45secs",
  },
  {
    unit_no: "NTM 414",
    postcode: "NE 19",
    status: false,
    last_broadcast: "10/05/2024",
    transmission_strength: 0,
    listening_time: "10hr20mins20secs",
  },
  {
    unit_no: "NTM 515",
    postcode: "NE 20",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 3,
    listening_time: "11hr5mins5secs",
  },
  {
    unit_no: "NTM 616",
    postcode: "NE 21",
    status: false,
    last_broadcast: "09/05/2024",
    transmission_strength: 0,
    listening_time: "12hr15mins15secs",
  },
  {
    unit_no: "NTM 717",
    postcode: "NE 22",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 4,
    listening_time: "13hr30mins30secs",
  },
  {
    unit_no: "NTM 818",
    postcode: "NE 23",
    status: false,
    last_broadcast: "08/05/2024",
    transmission_strength: 0,
    listening_time: "14hr45mins45secs",
  },
  {
    unit_no: "NTM 919",
    postcode: "NE 24",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 5,
    listening_time: "15hr10mins10secs",
  },
  {
    unit_no: "NTM 017",
    postcode: "NE 1",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 1,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 132",
    postcode: "NE 14",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 2,
    listening_time: "0hr37mins29secs",
  },
  {
    unit_no: "NTM 009",
    postcode: "NE 7",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 3,
    listening_time: "5hr28mins12secs",
  },
  {
    unit_no: "NTM 076",
    postcode: "NE 16",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 4,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 184",
    postcode: "NE 1",
    status: false,
    last_broadcast: "23/05/2024",
    transmission_strength: 0,
    listening_time: "7hr32mins18secs",
  },
  {
    unit_no: "NTM 068",
    postcode: "NE 9",
    status: false,
    last_broadcast: "23/05/2024",
    transmission_strength: 0,
    listening_time: "17hr2mins30secs",
  },
  {
    unit_no: "NTM 242",
    postcode: "NE 11",
    status: false,
    last_broadcast: "22/05/2024",
    transmission_strength: 0,
    listening_time: "8hr29mins24secs",
  },
  {
    unit_no: "NTM 027",
    postcode: "NE 5",
    status: false,
    last_broadcast: "20/05/2024",
    transmission_strength: 0,
    listening_time: "22hr25mins41secs",
  },
  {
    unit_no: "NTM 114",
    postcode: "NE 7",
    status: false,
    last_broadcast: "19/05/2024",
    transmission_strength: 0,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 190",
    postcode: "NE 2",
    status: false,
    last_broadcast: "16/05/2024",
    transmission_strength: 0,
    listening_time: "21hr53mins44secs",
  },
  {
    unit_no: "NTM 025",
    postcode: "NE 15",
    status: false,
    last_broadcast: "16/05/2024",
    transmission_strength: 0,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 101",
    postcode: "NE 3",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 5,
    listening_time: "2hr10mins30secs",
  },
  {
    unit_no: "NTM 202",
    postcode: "NE 4",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 3,
    listening_time: "3hr15mins45secs",
  },
  {
    unit_no: "NTM 303",
    postcode: "NE 5",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 2,
    listening_time: "4hr20mins50secs",
  },
  {
    unit_no: "NTM 404",
    postcode: "NE 6",
    status: false,
    last_broadcast: "15/05/2024",
    transmission_strength: 0,
    listening_time: "5hr30mins15secs",
  },
  {
    unit_no: "NTM 505",
    postcode: "NE 8",
    status: false,
    last_broadcast: "14/05/2024",
    transmission_strength: 0,
    listening_time: "6hr40mins25secs",
  },
  {
    unit_no: "NTM 606",
    postcode: "NE 10",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 4,
    listening_time: "2hr50mins10secs",
  },
  {
    unit_no: "NTM 017",
    postcode: "NE 1",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 1,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 132",
    postcode: "NE 14",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 2,
    listening_time: "0hr37mins29secs",
  },
  {
    unit_no: "NTM 009",
    postcode: "NE 7",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 3,
    listening_time: "5hr28mins12secs",
  },
  {
    unit_no: "NTM 076",
    postcode: "NE 16",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 4,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 184",
    postcode: "NE 1",
    status: false,
    last_broadcast: "23/05/2024",
    transmission_strength: 0,
    listening_time: "7hr32mins18secs",
  },
  {
    unit_no: "NTM 068",
    postcode: "NE 9",
    status: false,
    last_broadcast: "23/05/2024",
    transmission_strength: 0,
    listening_time: "17hr2mins30secs",
  },
  {
    unit_no: "NTM 242",
    postcode: "NE 11",
    status: false,
    last_broadcast: "22/05/2024",
    transmission_strength: 0,
    listening_time: "8hr29mins24secs",
  },
  {
    unit_no: "NTM 027",
    postcode: "NE 5",
    status: false,
    last_broadcast: "20/05/2024",
    transmission_strength: 0,
    listening_time: "22hr25mins41secs",
  },
  {
    unit_no: "NTM 114",
    postcode: "NE 7",
    status: false,
    last_broadcast: "19/05/2024",
    transmission_strength: 0,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 190",
    postcode: "NE 2",
    status: false,
    last_broadcast: "16/05/2024",
    transmission_strength: 0,
    listening_time: "21hr53mins44secs",
  },
  {
    unit_no: "NTM 025",
    postcode: "NE 15",
    status: false,
    last_broadcast: "16/05/2024",
    transmission_strength: 0,
    listening_time: "1hr53mins44secs",
  },
  // Additional entries to reach a total of 30
  {
    unit_no: "NTM 101",
    postcode: "NE 3",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 5,
    listening_time: "2hr10mins30secs",
  },
  {
    unit_no: "NTM 202",
    postcode: "NE 4",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 3,
    listening_time: "3hr15mins45secs",
  },
  {
    unit_no: "NTM 303",
    postcode: "NE 5",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 4,
    listening_time: "4hr20mins50secs",
  },
  {
    unit_no: "NTM 404",
    postcode: "NE 6",
    status: false,
    last_broadcast: "15/05/2024",
    transmission_strength: 0,
    listening_time: "5hr30mins15secs",
  },
  {
    unit_no: "NTM 505",
    postcode: "NE 8",
    status: false,
    last_broadcast: "14/05/2024",
    transmission_strength: 0,
    listening_time: "6hr40mins25secs",
  },
  {
    unit_no: "NTM 606",
    postcode: "NE 10",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 1,
    listening_time: "2hr50mins10secs",
  },
  {
    unit_no: "NTM 707",
    postcode: "NE 12",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 2,
    listening_time: "3hr30mins20secs",
  },
  {
    unit_no: "NTM 808",
    postcode: "NE 13",
    status: false,
    last_broadcast: "13/05/2024",
    transmission_strength: 0,
    listening_time: "4hr15mins35secs",
  },
  {
    unit_no: "NTM 909",
    postcode: "NE 14",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 5,
    listening_time: "5hr25mins45secs",
  },
  {
    unit_no: "NTM 010",
    postcode: "NE 15",
    status: false,
    last_broadcast: "12/05/2024",
    transmission_strength: 0,
    listening_time: "6hr50mins50secs",
  },
  {
    unit_no: "NTM 111",
    postcode: "NE 16",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 4,
    listening_time: "7hr15mins15secs",
  },
  {
    unit_no: "NTM 212",
    postcode: "NE 17",
    status: false,
    last_broadcast: "11/05/2024",
    transmission_strength: 0,
    listening_time: "8hr30mins30secs",
  },
  {
    unit_no: "NTM 313",
    postcode: "NE 18",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 2,
    listening_time: "9hr45mins45secs",
  },
  {
    unit_no: "NTM 414",
    postcode: "NE 19",
    status: false,
    last_broadcast: "10/05/2024",
    transmission_strength: 0,
    listening_time: "10hr20mins20secs",
  },
  {
    unit_no: "NTM 515",
    postcode: "NE 20",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 3,
    listening_time: "11hr5mins5secs",
  },
  {
    unit_no: "NTM 616",
    postcode: "NE 21",
    status: false,
    last_broadcast: "09/05/2024",
    transmission_strength: 0,
    listening_time: "12hr15mins15secs",
  },
  {
    unit_no: "NTM 717",
    postcode: "NE 22",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 4,
    listening_time: "13hr30mins30secs",
  },
  {
    unit_no: "NTM 818",
    postcode: "NE 23",
    status: false,
    last_broadcast: "08/05/2024",
    transmission_strength: 0,
    listening_time: "14hr45mins45secs",
  },
  {
    unit_no: "NTM 919",
    postcode: "NE 24",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 5,
    listening_time: "15hr10mins10secs",
  },
  {
    unit_no: "NTM 017",
    postcode: "NE 1",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 1,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 132",
    postcode: "NE 14",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 2,
    listening_time: "0hr37mins29secs",
  },
  {
    unit_no: "NTM 009",
    postcode: "NE 7",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 3,
    listening_time: "5hr28mins12secs",
  },
  {
    unit_no: "NTM 076",
    postcode: "NE 16",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 4,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 184",
    postcode: "NE 1",
    status: false,
    last_broadcast: "23/05/2024",
    transmission_strength: 0,
    listening_time: "7hr32mins18secs",
  },
  {
    unit_no: "NTM 068",
    postcode: "NE 9",
    status: false,
    last_broadcast: "23/05/2024",
    transmission_strength: 0,
    listening_time: "17hr2mins30secs",
  },
  {
    unit_no: "NTM 242",
    postcode: "NE 11",
    status: false,
    last_broadcast: "22/05/2024",
    transmission_strength: 0,
    listening_time: "8hr29mins24secs",
  },
  {
    unit_no: "NTM 027",
    postcode: "NE 5",
    status: false,
    last_broadcast: "20/05/2024",
    transmission_strength: 0,
    listening_time: "22hr25mins41secs",
  },
  {
    unit_no: "NTM 114",
    postcode: "NE 7",
    status: false,
    last_broadcast: "19/05/2024",
    transmission_strength: 0,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 190",
    postcode: "NE 2",
    status: false,
    last_broadcast: "16/05/2024",
    transmission_strength: 0,
    listening_time: "21hr53mins44secs",
  },
  {
    unit_no: "NTM 025",
    postcode: "NE 15",
    status: false,
    last_broadcast: "16/05/2024",
    transmission_strength: 0,
    listening_time: "1hr53mins44secs",
  },
  {
    unit_no: "NTM 101",
    postcode: "NE 3",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 5,
    listening_time: "2hr10mins30secs",
  },
  {
    unit_no: "NTM 202",
    postcode: "NE 4",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 3,
    listening_time: "3hr15mins45secs",
  },
  {
    unit_no: "NTM 303",
    postcode: "NE 5",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 2,
    listening_time: "4hr20mins50secs",
  },
  {
    unit_no: "NTM 404",
    postcode: "NE 6",
    status: false,
    last_broadcast: "15/05/2024",
    transmission_strength: 0,
    listening_time: "5hr30mins15secs",
  },
  {
    unit_no: "NTM 505",
    postcode: "NE 8",
    status: false,
    last_broadcast: "14/05/2024",
    transmission_strength: 0,
    listening_time: "6hr40mins25secs",
  },
  {
    unit_no: "NTM 606",
    postcode: "NE 10",
    status: true,
    last_broadcast: "Receiving",
    transmission_strength: 4,
    listening_time: "2hr50mins10secs",
  },
];
